### PR TITLE
Add code climate configuration

### PR DESCRIPTION
**Pull request by money**
https://osi-cwds.atlassian.net/browse/CODE-107

### CODE REVIEW

**Comment by eckdanny-osi** [comment]
seems a fine start... doesn't break anything

**Comment by money** [comment]
@NagaPradeepGajula-osi I am not sure how to enable the configuration.  Need your help with that.

**Comment by NagaPradeepGajula-osi** [comment]
@money to turn the CC check on each PR we need to have admin rights for the respective repo.
In this case @eckdanny-osi is the admin of this repo and may be he can help you?

**Comment by eckdanny-osi** [comment]
this repo is now an admin party for @ca-cwds/incredibles.

**Pull request merged**
