### PR TITLE
fix(www): add support target for ie11

### LINKED ISSUE #227: Guide site broken in IE11
reported on behalf of @vikas199 

screen_shot_2018-11-01_at_5 02 06_pm

### PR DESCRIPTION
**Pull request by eckdanny-osi**
Closes #227.

### CODE REVIEW

**Comment by vikas199** [comment]
@eckdanny-osi. This adds the support for IE versions 11 and more

**Comment by eckdanny-osi** [comment]
waiting on a preview deploy...: https://app.netlify.com/sites/cws-cares/deploys/5bdc9490fdd72a43a30d60e5

@vikas199 can you check in ie11?

**Comment by eckdanny-osi** [comment]
@vikas199 reported the preview deploy does NOT resolve the issue (via slack).

screen shot 2018-11-02 at 1 39 13 pm

I `curl`'d down `main.dd6c9e65.chunk.js` from the preview deploy and jumped to the relevant col in vim. 

screen shot 2018-11-02 at 1 38 15 pm

Looks like an arrow function is in the bundle. I'm thinking the root cause here is the MDX loader chain and our webpack inline syntax usage. Lemme hack on this for a little bit...

**Comment by eckdanny-osi** [comment]
gaining on it...

 > This preset uses the useBuiltIns option with transform-object-rest-spread and transform-react-jsx, which **assumes that Object.assign is available or polyfilled**.

**Comment by eckdanny-osi** [comment]
CRA@2 has its own recommended path for [adding polyfills](https://github.com/facebook/create-react-app/releases/tag/v2.0.3). The general case will be dependent upon consumer webpack/module-bundler configuration, but the _addition of polyfills at application bundling-time_ is consistent.

Cleaning up this PR now... 950bcd4 resolved some dangling es deps (e.g.; `Promise`, `Object.*`, ...) No js parse errors at least in ie11.0.9600 over parallels when running the devServer or the serving the production CRA build

**Comment by eckdanny-osi** [comment]
😢 The `react-app-polyfill/ie11` won't get us far [b/c of our usage of webpack inline loaders for the mdx chain?]. Using the (bloated) `babel-polyfill` package

**Pull request merged**
