### PR TITLE
adjust the set of fas icons used by CARES

### PR DESCRIPTION
**Pull request by eckdanny-osi**
The closed set of font awesome free solid svg icons that are defined by the design system as of now.

See [slack thread](https://ccwds.slack.com/archives/G9DLZG9B7/p1540597273020800) for context

### CODE REVIEW

**Comment by NagaPradeepGajula-osi** [comment]
Slack thread link says there's a glitch when accessed. Can you just throw a quick context here. 
Anyhow for me the icons addition looks good.

**Comment by eckdanny-osi** [comment]
@NagaPradeepGajula-osi _oops!_ Slack thread is a private channel. I'll paraphrase to establish context:

> A: CANS needs icon x, y, and z.
> B: The iconography should be consistent program-wide. The icons should convey the same meaning regardless of which app the user is in. Do we have a single source of truth for icons?
> C: Yes. `@cwds/icons`. Can you give me a blessed list of the icons that are in current state of DS?
> B: sure. *attaches file.

I'll try to remember not to paste links to private channel convos. Publics should be ok, but providing context manually is probably best. 👌

**Comment by NagaPradeepGajula-osi** [comment]
And are we going to just support this list of icons or do we have any more in the pipeline?

**Comment by eckdanny-osi** [comment]
Adding icons to our list (our `iconPack`) from the FontAwesome Free Solid set is trivial (a diff would look a lot like this PR).

I've clarified with designers that adding/removing of icons is technically easy. On the other hand, delivering a coherent + systematic iconography scheme (e.g. establishing an organizational standard for symbol meaning and usage) is harder. The latter is a design system concern. Requests for new icons should go through design.

**Pull request merged**
